version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/frontend
    exclude:
      - appspec.yml

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
